//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\projects\Chevin\Sandbox\FQL\FQL.Parser\FQLParser.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace FQL.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FQLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface IFQLParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FQLParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] FQLParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FQLParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] FQLParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FQLParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclaration([NotNull] FQLParser.VarDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringLiteral</c>
	/// labeled alternative in <see cref="FQLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] FQLParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>intLiteral</c>
	/// labeled alternative in <see cref="FQLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLiteral([NotNull] FQLParser.IntLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>var</c>
	/// labeled alternative in <see cref="FQLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] FQLParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FQLParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStatement([NotNull] FQLParser.PrintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>printInterpolationString</c>
	/// labeled alternative in <see cref="FQLParser.printParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintInterpolationString([NotNull] FQLParser.PrintInterpolationStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>printStringLiteral</c>
	/// labeled alternative in <see cref="FQLParser.printParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStringLiteral([NotNull] FQLParser.PrintStringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>printSymbolReference</c>
	/// labeled alternative in <see cref="FQLParser.printParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintSymbolReference([NotNull] FQLParser.PrintSymbolReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FQLParser.connectionString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConnectionString([NotNull] FQLParser.ConnectionStringContext context);
}
} // namespace FQL.Parser
